Repository hmcts/sscs-case-loader, pull requests merged in 2020-10, with the labels that each got.

#798 SSCS-8213: Tech debt – Upgrade Owasp to 6.x
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-798

#817 Suppress tomcat dependency
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-817

#819 updated config for security scan
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-819

#812 SSCS-8214 bump common
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-812
