Repository hmcts/sscs-case-loader, pull requests merged in 2020-08, with the labels that each got.

#737 SSCS-7823 - When an Appointee or Representative is added to a case via Caseloader, then the label does not update in CCD
  src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdAppellantData.java
  src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRepresentative.java
  src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseData.java
  src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdAppellantDataTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRepresentativeTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseDataTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-737

#749 SSCS-7535 Case Loader handle isScottish on case update
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/job/SscsCaseLoaderJobTest.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ProcessCaseTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/CaseLoaderApp.java
  src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java
  src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdCaseData.java
  src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRpc.java
  src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilder.java
  src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/TransformAppealCaseToCaseData.java
  src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSenderTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdRpcTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-749

#748 Enable functional tests for nightly pipeline
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-748

#752 Import GradleBuilder nightly
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-752

#753 Remove s from test url
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-753

#755 updated urls
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-755

#757 sscs-7911-updated urls of fix nightly job
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-757

#743 SSCS-7309 - Set 'Previous State' field when case moves to dormant
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-743

#762 Remove unused tf remote state
  infrastructure/state.tf
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-762

#763 enable functional tests on nightly test build
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-763

#765 Run functional tests at securityscan phase on Jenkins nightly test build
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-765

#766 Increase security alert to medium
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-766
