Repository hmcts/sscs-case-loader, pull requests merged in 2021-11, with the labels that each got.

#1155 Sscs 9731 added new column
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ReferenceDataServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1155

#1160 Suppress spring dependency check until version upgraded
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1160

#1156 Sscs 9732 venue
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilderTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilder.java
  src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataBuilderTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1156

#1159 Sscs 9750 amend gaps venue
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1159

#1169 Sscs 9800 update venue address
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/refdata/VenueDataLoaderTest.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ReferenceDataServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1169

#1175 Sscs 9836 upgrade to latest common
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1175

#1178 Sscs 9844
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1178
