Repository hmcts/sscs-case-loader, pull requests merged in 2021-08, with the labels that each got.

#1083 SSCS-9381: Enable fortify scan for nightly build
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1083

#1093 SSCS-9341 - BenefitType not found
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1093

#1098 Sscs 9498
  README.md
  src/main/java/uk/gov/hmcts/reform/sscs/exceptions/SftpCustomException.java
  src/main/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpChannelAdapter.java
  src/test/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpChannelAdapterTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1098

#1099 SSCS-9508 - BSPS - dwpAddress JSON
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1099

#1100 SSCS-9506 - Change Benefit name to Jobseeker’s Allowance (JSA)
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1100
