Repository hmcts/sscs-case-loader, pull requests merged in 2021-06, with the labels that each got.

#1038 Verify we have removed enough of the suppressions
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1038

#1034 SSCS-8820 - JSA DWP Office Address
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1034

#1059 SSCS-9331 - Address fortify backend issues
  src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1059

#1062 SSCS-9305 Refactor after moving deprecated fields
  build.gradle
  src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdAppellantDataTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1062

#1071 update security script
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1071
