Repository hmcts/sscs-case-loader, pull requests merged in 2021-09, with the labels that each got.

#1118 Sscs 9567 p1 flag
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1118

#1114 SSCS-9348 - Keep environment specific branches in sync with master
  Jenkinsfile_CNP
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1114

#1107 sscs 9490 added check for a void state
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderServiceTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/services/CaseLoaderService.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1107
