Repository hmcts/sscs-case-loader, pull requests merged in 2021-07, with the labels that each got.

#1074 SSCS-9061-updated common with social fund benefit type
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1074

#1065 SSCS-9308 - CCD UI – Setting the ESA and UC dwpRegionalCentrer
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1065

#1078 SSCS-8924 - Income Support
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1078

#1091 SSCS-8927- added assertions to ref data factory test
  build.gradle
  src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactoryTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1091

#1056 Sscs 9191 postponements
  src/main/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataEventBuilder.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/services/mapper/CaseDataEventBuilderTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1056
