Repository hmcts/sscs-case-loader, pull requests merged in 2021-05, with the labels that each got.

#995 SSCS-8900 - Attendance Allowance - Airlookup, DWP addresses & Robot Configuration
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-995

#1013 Suppress false positive CVE-2020-7791 since it is a C# CVE
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1013

#999 sscs 8879 update common
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-999

#1015 sscs 9066 update to jitpack
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1015

#1018 sscs 9066 move to release
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1018

#1019 Sscs 9088 improve caseloader
  src/e2e/resources/SSCS_CcdCases_Delta_2021-03-26-13-17-00.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1019

#1023 SSCS-8907 Add test to cover bereavement benefit
  src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactoryTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1023

#1025 SSCS-9041 - CCD UI – Validate DWP originating and presenting office for the 'Response reviewed' event
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1025

#1027 SSCS-8843: IIDB - Set Benefit Code to 067
  src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataFactoryTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1027
