Repository hmcts/sscs-case-loader, pull requests merged in 2021-12, with the labels that each got.

#1183 CVE-2021-22096 fix
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1183

#1181 Sscs 9777 ordering fix
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1181

#1189 Upgrade log4j to 2.15.0
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1189

#1192 suppress h2 warning
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1192
