Repository hmcts/sscs-case-loader, pull requests merged in 2021-02, with the labels that each got.

#898 Sscs 8607 illegal argument exception fix
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-898

#928 Sscs 8722 sscsdocument sorting
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-928

#932 SSCS-8684 - Upgrade Idam Client Only
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/CaseLoaderApp.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-932
