Repository hmcts/sscs-case-loader, pull requests merged in 2022-07, with the labels that each got.

#1355 SSCS-10706 Common bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1355

#1356 SSCS-10746-fix-cve
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1356

#1357 SSCS-10087 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1357
