Repository hmcts/sscs-case-loader, pull requests merged in 2022-05, with the labels that each got.

#1312 SSCS-10223 commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1312

#1295 SSCS-10388 Update Commons
  build.gradle
  dependency-check-suppressions.xml
  src/test/java/uk/gov/hmcts/reform/sscs/refdata/RefDataRepositoryTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1295

#1316 suppressing dependency
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1316

#1317 Disable fortify scan in nightly
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1317

#1315 sscs-10245 update sscs common version
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ReferenceDataServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1315

#1326 SSCS-10552-Tomcat-Upgrade: upgrade tomcat to 10.1.0-M15
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1326

#1333 SSCS-10561: upgrading build.gradle
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1333
