Repository hmcts/sscs-case-loader, pull requests merged in 2022-06, with the labels that each got.

#1335 SSCS-10445 Commons Bump
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1335

#1330 Update sscs common version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1330

#1337 Update build.gradle
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1337

#1342 SSCS-10286 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1342

#1343 SSCS-10643-Reference Data Update
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1343

#1345 SSCS-10620 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1345

#1346 SSCS-10242 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1346
