Repository hmcts/sscs-case-loader, pull requests merged in 2022-08, with the labels that each got.

#1361 update extension date
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1361

#1362 SSCS-10805-update-jar-version
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1362

#1364 SSCS-10773: Update commons version
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/job/SscsCaseLoaderJobTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1364

#1369 chore: increment sscs-common version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1369

#1370 Add backstage configuration file
  catalog-info.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1370

#1363 sscs-9874 common version update
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1363

#1372 SSCS-10841 Common bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1372
