Repository hmcts/sscs-case-loader, pull requests merged in 2022-10, with the labels that each got.

#1393 SSCS-10928 | Revert commons back to version that previously worked
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1393

#1396 SSCS-10985 CVE Fix Commons Bump
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1396

#1407 SSCS-11063 Use Renovate Shared Preset
  .github/renovate.json
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1407
