Repository hmcts/sscs-case-loader, pull requests merged in 2022-04, with the labels that each got.

#1278 Update build.gradle
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1278

#1281 Update build.gradle
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1281

#1289 SSCS-10220 Update to common RC version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1289

#1299 Update commons
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1299

#1286 SSCS-10146 update sscs-common version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1286

#1302 SSCS-10387 Update Commons
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1302

#1308 SSCS-10434 Update Spring Core
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1308
