Repository hmcts/sscs-case-loader, pull requests merged in 2023-08, with the labels that each got.

#1474 Revert commons to 4.26.2
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1474

#1475 revert caseloader -1
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1475

#1476 revert app insights
  .gitignore
  Dockerfile
  build.gradle
  charts/sscs-case-loader/Chart.yaml
  charts/sscs-case-loader/values.yaml
  lib/AI-Agent.xml
  lib/applicationinsights.json
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1476

#1477 revert sscs commons from 4.26.4 to 4.26.2
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1477

#1481 Fixup gradle file
  build.gradle
  dependency-check-suppressions.xml
  src/e2e/java/uk/gov/hmcts/reform/tools/utils/CaseIdMapUtils.java
  src/test/java/uk/gov/hmcts/reform/sscs/services/sftp/SftpChannelAdapterTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1481
