Repository hmcts/sscs-case-loader, pull requests merged in 2023-06, with the labels that each got.

#1460 CVE Fix 01.06.2023
  charts/sscs-case-loader/Chart.yaml
  dependency-check-suppressions.xml
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ccd/SearchCcdServiceByCaseIdRetryAndRecoverTest.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ccd/SearchCcdServiceByCaseIdTest.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/services/ccd/UpdateCcdServiceRetryAndRecoverTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1460

#1464 CVE Suppression - 12.06.2023
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1464

#1462 SSCS -11749 ( SSCS 2 cases are not being updated by caseloader )
  src/main/java/uk/gov/hmcts/reform/sscs/models/deserialize/gaps2/AppealCase.java
  src/main/java/uk/gov/hmcts/reform/sscs/services/TransformationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/services/TransformationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1462

#1465 SSCS-11771-Fortify-security-issue
  docker-compose.yml
  docker/sftp-docker
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1465

#1468 SSCS-11771-Fortify-security-issue
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1468

#1470 CVEFix - 27.06.23
  Jenkinsfile_nightly
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1470

#1471 CVE Fix - 30.06.23
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1471
