Repository hmcts/sscs-case-loader, pull requests merged in 2023-04, with the labels that each got.

#1432 dockerfile tag change
  Dockerfile
  build.gradle
  charts/sscs-case-loader/Chart.yaml
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1432

#1433 CVE-06.04.23
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1433

#1453 dependencySet(group: 'org.springframework', version: '5.2.24.RELEASE')
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1453

#1455 Remove security script
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1455
