Repository hmcts/sscs-case-loader, pull requests merged in 2024-02, with the labels that each got.

#1507 SSCISCI-677: stop NPE when language is null
  src/main/java/uk/gov/hmcts/reform/sscs/job/DataMigrationJob.java
  src/main/java/uk/gov/hmcts/reform/sscs/services/DataMigrationService.java
  src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java
  src/main/java/uk/gov/hmcts/reform/sscs/util/MigrationDataEncoderApp.java
  src/main/java/uk/gov/hmcts/reform/sscs/util/MigrationStringUtils.java
  src/test/java/uk/gov/hmcts/reform/sscs/job/DataMigrationJobTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/services/DataMigrationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/util/MigrationStringUtilsTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1507

#1509 Update suppressions
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1509

#1510 Update suppressions
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1510
