Repository hmcts/sscs-case-loader, pull requests merged in 2024-07, with the labels that each got.

#1528 Update suppression date
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1528

#1527 SSCSCI-870: update venue migration
  build.gradle
  charts/sscs-case-loader/Chart.yaml
  charts/sscs-case-loader/values.yaml
  src/main/java/uk/gov/hmcts/reform/sscs/job/ProcessingVenueMigrationJob.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/job/ProcessingVenueMigrationJobTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1527

#1531 Upgrade sscs-common, update Reading venue address
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1531
