Repository hmcts/sscs-case-loader, pull requests merged in 2024-12, with the labels that each got.

#1558 Bump common as new event type is added
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1558

#1560 SSCSSI-247: Update to sscs commons
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1560

#1561 SSCSCI-1347 commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1561

#1564 commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1564
