Repository hmcts/sscs-case-loader, pull requests merged in 2024-11, with the labels that each got.

#1544 SSCSCI-995-jackson-databind-bump
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1544

#1551 SSCSSI-98-21: C4: hearingBooked - ProcessHmcMessageService
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1551

#1553 Bump common to latest version(include enum changes for add hearing outcome)
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1553

#1554 SSCSCI-1406: Bumping up commons
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1554

#1555 SSCSCI-1345 commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1555
