Repository hmcts/sscs-case-loader, pull requests merged in 2024-03, with the labels that each got.

#1512 Update suppressions
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1512

#1514 Update sscs-common to 5.3.6
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1514

#1515 CVE dependency patches and minors
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1515

#1511 SSCSCI-763: processingVenue migration
  charts/sscs-case-loader/Chart.yaml
  charts/sscs-case-loader/values.yaml
  src/main/java/uk/gov/hmcts/reform/sscs/config/CaseLoaderJobConfig.java
  src/main/java/uk/gov/hmcts/reform/sscs/job/CaseLoaderTasklet.java
  src/main/java/uk/gov/hmcts/reform/sscs/job/DataMigrationJob.java
  src/main/java/uk/gov/hmcts/reform/sscs/job/InterpreterMigrationJob.java
  src/main/java/uk/gov/hmcts/reform/sscs/job/ProcessingVenueMigrationJob.java
  src/main/java/uk/gov/hmcts/reform/sscs/services/DataMigrationService.java
  src/main/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSender.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/job/CaseLoaderTaskletTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/job/DataMigrationJobTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/job/InterpreterMigrationJobTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/job/ProcessingVenueMigrationJobTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/services/DataMigrationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/services/ccd/CcdCasesSenderTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1511

#1519 SSCSCI-677: add venue migration secret
  charts/sscs-case-loader/Chart.yaml
  charts/sscs-case-loader/values.yaml
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1519
