Repository hmcts/sscs-case-loader, pull requests merged in 2025-05, with the labels that each got.

#1600 Bump suppression valid until date
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1600

#1601 commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1601

#1602 commons pointing
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1602

#1603 SSCSCI-1862: sscs-common bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1603
