Repository hmcts/sscs-case-loader, pull requests merged in 2025-01, with the labels that each got.

#1565 SSCSCI-1547 commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1565

#1566 SSCSCI-1428: sscs-common bump
  build.gradle
Labels: ns:sscs, prd:sscs

#1567 SSCSCI-1205: update sscs-common
  build.gradle
Labels: ns:sscs, prd:sscs

#1568 Sscsci 1536: Bump commons
  build.gradle
Labels: ns:sscs, prd:sscs

#1569 SSCSCI-1531
  build.gradle
Labels: ns:sscs, prd:sscs

#1570 SSCSCI-1607 Test sb3 sscs-commons
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1570
