Repository hmcts/sscs-case-loader, pull requests merged in 2025-03, with the labels that each got.

#1580 SSCSCI-1778
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1580

#1579 test common elastic search changes
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1579

#1583 common bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1583

#1585 SSCSCI-1787: Helm chart update
  charts/sscs-case-loader/Chart.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1585

#1587 SSCSCI-1719 commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1587
