Repository hmcts/sscs-case-loader, pull requests merged in 2025-07, with the labels that each got.

#1618 Extending suppression date as there is no fix available upstream
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1618

#1623 upgrade to secs-common 6.3.7
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1623

#1624 Upgrade sscs-common to v6.3.8
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1624

#1626 SSCSCI dependency check error fix
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1626
