Repository hmcts/sscs-case-loader, pull requests merged in 2025-04, with the labels that each got.

#1591 Revert common jar version due to latest version being broken
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1591

#1593 SSCSCI-1832: remove duplicate outdated commons-io dep
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1593

#1595 Bump suppression valid until date
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1595

#1596 update sscs-common
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1596

#1597 SSCSCI-1789: sscs-common bump to 6.2.2
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1597
