Repository hmcts/sscs-case-loader, pull requests merged in 2025-02, with the labels that each got.

#1571 SSCSCI-1563 / SSCSCI-1439 commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1571

#1573 commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-case-loader-pr-1573

#1572 SSCSCI-1623: AzureRM bump to 4.15.0
  config/owasp/suppressions.xml
  infrastructure/.terraform-version
  infrastructure/state.tf
Labels: ns:sscs, prd:sscs, aat/add-or-update, prod/add-or-update, rel:sscs-case-loader-pr-1572
